services:
  postgres:
    image: postgres:16
    env_file:
      - ./docker.env
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: